spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://3.37.244.96:5432/kotlindb
    username: master_user_01
    password: master
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      # 운영 시
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #실행 시 warning 제거
    properties:
      hibernate:
        # 최신 pgJDBC Drivre 사용하기 위한 설정
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: false
        jdbc:
          lob:
            non_contextual: true
  naver:
    keyId: vx9h5vmrlv
    key: i98LkMbKgEUC5oQ8TFaVVqA5b7ua9374shnlFtFM
  # 콘솔창 출력 시 색상 부여
  output:
    ansi:
      enabled: always
logging:
  config: classpath:log4j2.yml


---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://ec2-3-36-178-40.ap-northeast-2.compute.amazonaws.com:33095/mini2S?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: david
    password: dalock2dev

  jpa :
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate :
      # Schema 자동 업데이트, Entity와 비교해서, 길이 변경은 제외
      hbm2ddl.auto : update
      # 보여지는 SQL을 예쁘게 보여줌
      format_sql : true
    showSql : true
    generate-ddl : true
    # WARN 23008 에러 제거
    open-in-view: false

  naver:
    keyId: vx9h5vmrlv
    key: i98LkMbKgEUC5oQ8TFaVVqA5b7ua9374shnlFtFM