package com.mini2S.entity;

public class Contracts {
    /*
        계약ID	CONTRACT_ID	VARCHAR	100
        상태	STATUS	VARCHAR	10
        사용자ID	USER_ID	VARCHAR	100
        관리자ID	MANAGER_ID	VARCHAR	100
        고객타입	CUSTOMER_TYPE	VARCHAR	10
        고객명	USER_NAME	VARCHAR	100
        전화번호	PHONE_NUMBER	VARCHAR	20
        이메일	EMAIL	VARCHAR	100
        주소	ADDRESS1	VARCHAR	100
        상세주소	ADDRESS2	VARCHAR	100
        우편번호	ZIPCODE	VARCHAR	16
        팩스번호	FAX_NUMBER	VARCHAR	20
        비상연락(성명)	EMRGN_CNTCT_NAME	VARCHAR	100
        비상연락(번호)	EMRGN_CNTCT_PHONE	VARCHAR	20
        지점ID	BRANCH_ID	VARCHAR	100
        지점명	BRANCH_NAME	VARCHAR	100
        상품타입ID	PRODUCT_TYPE_ID	VARCHAR	100
        상품타입명	PRODUCT_TYPE_NAME	VARCHAR	100
        룸ID	ROOM_ID	VARCHAR	100
        룸이름	ROOM_NAME	VARCHAR	100
        룸사이즈	ROOM_SIZE	VARCHAR	100
        이용시작일자	START_DTTM	TIMESTAMP
        이용종료일자	END_DTTM	TIMESTAMP
        이용개월수	MONTH	INT	11
        이용일수	DAY	INT	11
        기본할인상한선	LIMIT_BASE_DISCOUNT_RATE	INT	11
        총할인상한선	LIMIT_TOTAL_DISCOUNT_RATE	INT	11
        룸가격	ROOM_PRICE	INT	11
        기본가격	BASE_PRICE	INT	11
        약정할인ID	AG_DISCOUNT_ID	VARCHAR	100
        약정할인명	AG_DISCOUNT_NAME	VARCHAR	100
        약정할인기준개월수	AG_DISCOUNT_MONTH	INT	11
        약정할인율	AG_DISCOUNT_RATE	INT	11
        약정할인실제할인액	AG_DISCOUNT_ACTUAL_AMT	INT	11
        룸할인ID	RO_DISCOUNT_ID	VARCHAR	100
        룸할인명	RO_DISCOUNT_NAME	VARCHAR	100
        룸할인율	RO_DISCOUNT_RATE	INT	11
        룸실제할인액	RO_DISCOUNT_ACTUAL_AMT	INT	11
        프로모션할인ID	PR_DISCOUNT_ID	VARCHAR	100
        프로모션할인명	PR_DISCOUNT_NAME	VARCHAR	100
        프로모션할인율	PR_DISCOUNT_RATE	INT	11
        프로모션실제할인율	PR_DISCOUNT_ACTUAL_AMT	INT	11
        기본할인율	BASE_DISCOUNT_RATE	INT	11
        기본실제할인금액	BASE_DISCOUNT_ACTUAL_AMT	INT	11
        이용할인ID	US_DISCOUNT_ID	VARCHAR	100
        이용할인명	US_DISCOUNT_NAME	VARCHAR	100
        이용할인율	US_DISCOUNT_RATE	INT	11
        이용실제할인금액	US_DISCOUNT_ACTUAL_AMT	INT	11
        기타할인ID	ETC_DISCOUNT_ID	VARCHAR	100
        기타할인명	ETC_DISCOUNT_NAME	VARCHAR	100
        기타할인율	ETC_DISCOUNT_RATE	INT	11
        기타할인금액	ETC_DISCOUNT_AMT	INT	11
        기타실제할인금액	ETC_DISCOUNT_ACTUAL_AMT	INT	11
        즉시할인명	INSTANT_DISCOUNT_NAME	VARCHAR	100
        즉시할인율	INSTANT_DISCOUNT_RATE	INT	11
        즉시할인금액	INSTANT_DISCOUNT_AMT	INT	11
        즉시할인실제할인금액	INSTANT_DISCOUNT_ACTUAL_AMT	INT	11
        운송ID	TRANSPORT_ID	VARCHAR	100
        이용가격	PRICE_USAGE	INT	11
        물품가격	PRICE_GOODS	INT	11
        예치금	DEPOSIT	INT	11
        예치금VAT	DEPOSIT_VAT	INT	11
        예치금상태	DEPOSIT_STATUS	VARCHAR	100
        운송금액	PRICE_TRANSPORT	INT	11
        종료신청금액	PRICE_END	INT	11
        기타금액	PRICE_ETC	INT	11
        총금액	PRICE_TOTAL	INT	11
        총금액VAT	PRICE_TOTAL_VAT	INT	11
        특약사항	SPECIAL_CONTRACT	MEDIUMTEXT
        메모	NOTE	LONGTEXT
        견적일자	ESTIMATE_DTTM	TIMESTAMP
        계약일자	CONTRACT_DTTM	TIMESTAMP
        월이용금액(+VAT)	PRICE_MONTH_VAT	INT	11
        기준일자	DATE	INT	11
        연체금	ARREARS	INT	11
        월별이용금액(+VAT)	PRICE_MONTH_USAGE_VAT	INT	11
        월별물품금액(+VAT)	PRICE_MONTH_GOODS_VAT	INT	11
        위약금	PENALTY	INT	11
        프로모션위약금	PROMO_PENALTY	INT	11
        출고운송가격	PRICE_OUT_TRANSPORT	INT	11
        처분일	DISPOSAL_DTTM	TIMESTAMP
        이전계약ID	PREV_CONTRACT_ID	VARCHAR	100
    */
}
